### ISSUE TITLE
Sparse matricies?

### ISSUE THREAD

**Issue by brandondube** [nsomatilda/Matilda#1]
:wave: hello there -- author from the same SPIE proceedings as you, wondering if you have thought about sparse matricies as well, particularly in CSR form?

As a motivation, consider a wavefront sensor that produces a 4 megapixel image of a pupil, and that such a high resolution image really does contain mostly the minimum useful information.  And assume you are using 96x96 DMs, such as for HWO.  Then a naïve control interaction matrix is ~1.2TiB.  But, if only a 5 x 5 actuator tile is considered for each actuator, then the sparsity factor is about 380x, and the nonzero elements are less than 4 GiB.  

Just wondering whether this is an interesting development for y'all or not, cheers.

**Comment by nsomatilda** [comment]
Hi there, thanks for reaching out. There are no plans for sparse matrices at this point.
